import { StyleSheet } from "react-native";

export const calculateStyle = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F6F8FB",
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
    paddingVertical: 24,
  },
  centerBlock: {
    width: "100%",
  },
  header: {
    marginBottom: 22,
    alignItems: "center",
  },
  eyebrow: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.4,
    color: "#64748B",
    marginBottom: 10,
    textAlign: "center",
  },
  title: {
    fontSize: 30,
    fontWeight: "800",
    color: "#0F172A",
    marginBottom: 8,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 14,
    lineHeight: 21,
    color: "#64748B",
    textAlign: "center",
    maxWidth: 320,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    padding: 20,
    borderWidth: 1,
    borderColor: "#E7EDF5",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 22,
    elevation: 4,
  },
  resultPanel: {
    backgroundColor: "#F8FAFC",
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#EAEFF5",
  },
  resultCaption: {
    fontSize: 12,
    fontWeight: "700",
    color: "#64748B",
    marginBottom: 6,
    letterSpacing: 0.4,
  },
  resultValue: {
    fontSize: 38,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 6,
  },
  expressionText: {
    fontSize: 14,
    color: "#64748B",
    fontWeight: "600",
  },
  fieldGroup: {
    marginBottom: 16,
  },
  label: {
    fontSize: 13,
    fontWeight: "700",
    color: "#334155",
    marginBottom: 8,
  },
  input: {
    height: 56,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 16,
    fontSize: 16,
    color: "#0F172A",
  },
  operationsWrapper: {
    marginTop: 4,
    marginBottom: 10,
  },
  sectionLabel: {
    fontSize: 13,
    fontWeight: "800",
    color: "#334155",
    marginBottom: 12,
    letterSpacing: 0.3,
  },
  operationsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  operationButton: {
    width: "48.5%",
    minHeight: 72,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  operationButtonActive: {
    backgroundColor: "#111827",
    borderColor: "#111827",
  },
  operationButtonPressed: {
    transform: [{ scale: 0.98 }],
  },
  operationSymbol: {
    fontSize: 22,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 4,
  },
  operationText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#334155",
  },
  operationTextActive: {
    color: "#FFFFFF",
  },
  errorText: {
    marginTop: 4,
    marginBottom: 14,
    color: "#DC2626",
    fontSize: 13,
    fontWeight: "600",
  },
  actionsRow: {
    flexDirection: "row",
    marginTop: 4,
  },
  primaryButton: {
    flex: 1,
    height: 56,
    borderRadius: 18,
    backgroundColor: "#2563EB",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 6,
  },
  primaryButtonDisabled: {
    backgroundColor: "#BFDBFE",
  },
  primaryButtonPressed: {
    transform: [{ scale: 0.985 }],
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "800",
  },
  secondaryButton: {
    width: 116,
    height: 56,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 6,
  },
  secondaryButtonPressed: {
    transform: [{ scale: 0.985 }],
  },
  secondaryButtonText: {
    color: "#0F172A",
    fontSize: 15,
    fontWeight: "700",
  },
});